apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-catalog
  title: test-catalog
  description: test-catalog
  tags:
    - backend
    - node
  annotations:
    github.com/project-repo: enio1303/test-catalog
    github.com/build-definition: test-catalog
spec:
  type: openapi
  lifecycle: production
  owner: bmg-cdev-dev
